from commands.base import *
from commands.help import *
from commands.pingpong import *
from commands.tags import *
#from commands.highnoon import *
from commands.someone import *
from commands.archive import *
from commands.leaderboard import *
from commands.playing import *
from commands.crashme import *
