from commands.base import *
from commands.help import *
from commands.pingpong import *
from commands.tags import *
from commands.sounds import *
from commands.someone import *
from commands.archive import *
from commands.leaderboard import *
from commands.playing import *
from commands.crashme import *
from commands.music import *
from commands.poll import *
from commands.twitch import *
